### ISSUE TITLE
Initial Menu Screen

### ISSUE THREAD

**Issue by praddyinstant** [vikaspro90/Can-Knockdown-VR#2]
Create a HUD in the beginning of Game play.

**Comment by praddyinstant** [comment]
Vikas created a Menu scene with Raycasting to select different game levels and to start the play.

**Comment by vikaspro90** [comment]
Normal canvas menus do not interact with normal ray casting. One way was to use a graphics raycast. But instead we went ahead with creating 3d objects for panels and buttons and saved them as prefabs for reuse.
