### ISSUE TITLE
Place for holding the Balls and Haptic Feedback for picking up the ball

### ISSUE THREAD

**Issue by praddyinstant** [vikaspro90/Can-Knockdown-VR#6]
- Add the closing of Hand when the balls is picked up.
- Plan for a place for the balls.
- Create haptic feedback when hand touches the ball.

**Comment by vikaspro90** [comment]
Hand closing requires skills in a modeling and animation software like blender. Not enough time to spend on it. Not fixing.
Using a 3rd party asset barrel as an urn for holding the balls.
Haptic feedback added by @praddyinstant
